from typing import Protocol

from app.domain.accounting.entities import JournalEntry
from app.domain.goods_receipt.entities import GoodsReceipt
from app.domain.payment.entities import Payment
from app.domain.purchase_order.entities import PurchaseOrder
from app.domain.purchase_requisition.entities import PurchaseRequisition


class PRRepository(Protocol):
    def add(self, pr: PurchaseRequisition) -> PurchaseRequisition: ...
    def get(self, pr_id: int) -> PurchaseRequisition | None: ...
    def list(self) -> list[PurchaseRequisition]: ...
    def update(self, pr: PurchaseRequisition) -> None: ...


class PORepository(Protocol):
    def add(self, po: PurchaseOrder) -> PurchaseOrder: ...
    def get(self, po_id: int) -> PurchaseOrder | None: ...
    def list(self) -> list[PurchaseOrder]: ...
    def update(self, po: PurchaseOrder) -> None: ...


class GRRepository(Protocol):
    def add(self, gr: GoodsReceipt) -> GoodsReceipt: ...
    def get(self, gr_id: int) -> GoodsReceipt | None: ...
    def list(self) -> list[GoodsReceipt]: ...
    def update(self, gr: GoodsReceipt) -> None: ...


class PaymentRepository(Protocol):
    def add(self, payment: Payment) -> Payment: ...
    def get(self, payment_id: int) -> Payment | None: ...
    def list(self) -> list[Payment]: ...
    def update(self, payment: Payment) -> None: ...
    def get_by_gr_id(self, gr_id: int) -> Payment | None: ...


class JournalRepository(Protocol):
    def add(self, entry: JournalEntry) -> JournalEntry: ...
    def list(self) -> list[JournalEntry]: ...


class UnitOfWork(Protocol):
    pr_repo: PRRepository
    po_repo: PORepository
    gr_repo: GRRepository
    payment_repo: PaymentRepository
    journal_repo: JournalRepository

    def __enter__(self) -> "UnitOfWork": ...
    def __exit__(self, *args) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
